import { PageHeader, Card, Badge, Stat, Th, Td, TableWrap } from "@/components/ui/kit";
import { PriceChart } from "@/components/charts/charts";
import { priceDay } from "@/lib/data/series";

export default function MarketPage() {
  const prices = priceDay(21);

  const drivers = [
    { k: "TTF gas (front month)", v: "€31.4/MWh", d: "▲ 2.1%", up: false },
    { k: "Terna demand forecast D+1", v: "37.2 GW peak", d: "▲ 1.2 GW (heatwave)", up: false },
    { k: "Solar penetration D+1", v: "41% at H13", d: "duck-curve depth −€34", up: true },
    { k: "France IT-FR interconnector", v: "2.6 GW import", d: "congestion low", up: true },
    { k: "Hydro reservoirs (North)", v: "78% fill", d: "▲ 6pp vs 5y avg", up: true },
  ];

  return (
    <>
      <PageHeader
        eyebrow="Intelligence · Market"
        title="Price forecasting & market drivers"
        desc="Hourly PUN and zonal forecasts with confidence intervals, volatility and negative-price probability — the price leg of every bid the optimizer builds."
        right={<Badge tone="teal">GME feed · results 12:55 CET</Badge>}
      />

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <Stat label="PUN D+1 average" value="€92.4" unit="/MWh" delta="▲ 1.8% d/d" tone="down" />
        <Stat label="Evening peak H19–H21" value="€134" unit="/MWh" foot="capture opportunity" tone="solar" delta="BESS target" />
        <Stat label="P(neg. price) H13 SUD" value="11" unit="%" tone="down" delta="cap offers at €0" foot="solar oversupply" />
        <Stat label="Price MAE · 30d" value="€6.8" unit="/MWh" foot="pun-price-v6" />
      </div>

      <div className="grid lg:grid-cols-3 gap-4">
        <Card className="lg:col-span-2" title="D+1 hourly price forecast" sub="PUN with P10–P90 · zonal spreads SICI / SUD / SARD">
          <PriceChart data={prices} />
        </Card>

        <Card title="Fundamental drivers" sub="What the model is reading right now" pad={false}>
          <TableWrap>
            <thead><tr><Th>Driver</Th><Th>Level</Th><Th>Signal</Th></tr></thead>
            <tbody>
              {drivers.map((r) => (
                <tr key={r.k}>
                  <Td><span className="text-[12.5px]">{r.k}</span></Td>
                  <Td><span className="font-mono text-[12px] tabular-nums">{r.v}</span></Td>
                  <Td><span className={`font-mono text-[11.5px] ${r.up ? "text-up" : "text-down"}`}>{r.d}</span></Td>
                </tr>
              ))}
            </tbody>
          </TableWrap>
          <div className="px-5 py-4 border-t border-linesoft">
            <div className="eyebrow mb-2">Model commentary · generated by HELIOS</div>
            <p className="text-[12.5px] text-muted leading-relaxed">
              Heatwave demand lifts the evening peak while record solar depresses H12–H15. Zonal spread SICI−PUN widens to
              €7.3 on cable congestion — favor Sicilian BESS discharge into H19–H21 and cap SUD midday offers at zero.
            </p>
          </div>
        </Card>
      </div>
    </>
  );
}
